DROP TABLE IF EXISTS TOOL;
CREATE TABLE TOOL (
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR(4) NOT NULL,
TYPE VARCHAR(20) NOT NULL,
BRAND VARCHAR(20) NOT NULL,
DAILY_CHARGE NUMERIC NOT NULL,
WEEKDAY_CHARGE NUMBER(1,0) NOT NULL,
WEEKEND_CHARGE NUMBER(1,0) NOT NULL,
HOLIDAY_CHARGE NUMBER(1,0) NOT NULL
);